package org.generatedDao;
// Generated Aug 25, 2024, 1:33:37 AM by Hibernate Tools 6.5.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="ecommerce"
    , uniqueConstraints = {@UniqueConstraint(columnNames="admin_name"), @UniqueConstraint(columnNames="email")} 
)
public class Admin  implements java.io.Serializable {


     private int adminId;
     private String adminName;
     private String email;
     private String password;

    public Admin() {
    }

    public Admin(int adminId, String adminName, String email, String password) {
       this.adminId = adminId;
       this.adminName = adminName;
       this.email = email;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="admin_id", unique=true, nullable=false)
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="admin_name", unique=true, nullable=false, length=45)
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


