package org.generatedDao;
// Generated Aug 25, 2024, 1:33:37 AM by Hibernate Tools 6.5.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Interests generated by hbm2java
 */
@Entity
@Table(name="interests"
    ,catalog="ecommerce"
)
public class Interests  implements java.io.Serializable {


     private int interestsId;
     private String name;
     private Set<User> users = new HashSet<User>(0);

    public Interests() {
    }

	
    public Interests(int interestsId, String name) {
        this.interestsId = interestsId;
        this.name = name;
    }
    public Interests(int interestsId, String name, Set<User> users) {
       this.interestsId = interestsId;
       this.name = name;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="interests_id", unique=true, nullable=false)
    public int getInterestsId() {
        return this.interestsId;
    }
    
    public void setInterestsId(int interestsId) {
        this.interestsId = interestsId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_interests", catalog="ecommerce", uniqueConstraints={@UniqueConstraint(columnNames="interests_interests_id"), @UniqueConstraint(columnNames="user_user_id")}, joinColumns = { 
        @JoinColumn(name="interests_interests_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_user_id", unique=true, nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


