package org.generatedDao;
// Generated Aug 25, 2024, 11:51:02 AM by Hibernate Tools 6.5.0.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="ecommerce"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private Category category;
     private String productName;
     private String description;
     private Integer quantity;
     private Integer price;
     private Set<ProductsInsideCart> productsInsideCarts = new HashSet<ProductsInsideCart>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Product() {
    }

	
    public Product(int productId, Category category, String productName, String description) {
        this.productId = productId;
        this.category = category;
        this.productName = productName;
        this.description = description;
    }
    public Product(int productId, Category category, String productName, String description, Integer quantity, Integer price, Set<ProductsInsideCart> productsInsideCarts, Set<Order> orders) {
       this.productId = productId;
       this.category = category;
       this.productName = productName;
       this.description = description;
       this.quantity = quantity;
       this.price = price;
       this.productsInsideCarts = productsInsideCarts;
       this.orders = orders;
    }
   
     @Id 

    
    @Column(name="product_id", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<ProductsInsideCart> getProductsInsideCarts() {
        return this.productsInsideCarts;
    }
    
    public void setProductsInsideCarts(Set<ProductsInsideCart> productsInsideCarts) {
        this.productsInsideCarts = productsInsideCarts;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_products", catalog="ecommerce", uniqueConstraints={@UniqueConstraint(columnNames="order_id"), @UniqueConstraint(columnNames="product_id")}, joinColumns = { 
        @JoinColumn(name="product_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="order_id", unique=true, nullable=false, updatable=false) })
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


