package org.generatedDao;
// Generated Aug 25, 2024, 11:51:02 AM by Hibernate Tools 6.5.0.Final


import jakarta.persistence.*;

/**
 * ProductsInsideCart generated by hbm2java
 */
@Entity
@Table(name="products_inside_cart"
    ,catalog="ecommerce"
)
public class ProductsInsideCart  implements java.io.Serializable {


     private ProductsInsideCartId id;
     private User user;
     private Product product;
     private String productQuantity;

    public ProductsInsideCart() {
    }

	
    public ProductsInsideCart(ProductsInsideCartId id, User user, Product product) {
        this.id = id;
        this.user = user;
        this.product = product;
    }
    public ProductsInsideCart(ProductsInsideCartId id, User user, Product product, String productQuantity) {
       this.id = id;
       this.user = user;
       this.product = product;
       this.productQuantity = productQuantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public ProductsInsideCartId getId() {
        return this.id;
    }
    
    public void setId(ProductsInsideCartId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="product_quantity", length=45)
    public String getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(String productQuantity) {
        this.productQuantity = productQuantity;
    }




}


