package org.generatedDao;
// Generated Aug 25, 2024, 1:33:37 AM by Hibernate Tools 6.5.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="ecommerce"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class User  implements java.io.Serializable {


     private int userId;
     private String userName;
     private float balance;
     private String address;
     private String email;
     private String password;
     private Date birthDate;
     private Set<Interests> interestses = new HashSet<Interests>(0);
     private Set<BalanceLogs> balanceLogses = new HashSet<BalanceLogs>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public User() {
    }

	
    public User(int userId, String userName, float balance, String address, String email, String password) {
        this.userId = userId;
        this.userName = userName;
        this.balance = balance;
        this.address = address;
        this.email = email;
        this.password = password;
    }
    public User(int userId, String userName, float balance, String address, String email, String password, Date birthDate, Set<Interests> interestses, Set<BalanceLogs> balanceLogses, Set<Cart> carts, Set<Order> orders) {
       this.userId = userId;
       this.userName = userName;
       this.balance = balance;
       this.address = address;
       this.email = email;
       this.password = password;
       this.birthDate = birthDate;
       this.interestses = interestses;
       this.balanceLogses = balanceLogses;
       this.carts = carts;
       this.orders = orders;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="balance", nullable=false, precision=12)
    public float getBalance() {
        return this.balance;
    }
    
    public void setBalance(float balance) {
        this.balance = balance;
    }

    
    @Column(name="address", nullable=false, length=255)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_interests", catalog="ecommerce", uniqueConstraints={@UniqueConstraint(columnNames="interests_interests_id"), @UniqueConstraint(columnNames="user_user_id")}, joinColumns = { 
        @JoinColumn(name="user_user_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="interests_interests_id", unique=true, nullable=false, updatable=false) })
    public Set<Interests> getInterestses() {
        return this.interestses;
    }
    
    public void setInterestses(Set<Interests> interestses) {
        this.interestses = interestses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<BalanceLogs> getBalanceLogses() {
        return this.balanceLogses;
    }
    
    public void setBalanceLogses(Set<BalanceLogs> balanceLogses) {
        this.balanceLogses = balanceLogses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


